### ISSUE TITLE
Fork instead of releasing from the upstream?

### ISSUE THREAD

**Issue by 130s** [Eurecat/abseil_cpp-release#1]
Looks like the devel repo of the ROS version, https://github.com/Eurecat/abseil-cpp, is a fork. Is there any reason why you released from fork instead of the [upstream origin](https://github.com/abseil/abseil-cpp)? I understand that the upstream maintainer may not agree with making a release into ROS, but by forking you're adding maintenance responsibility of synchronizing code if we choose to do so.

(If they like the idea of releasing into ROS, by the way, there's a [tutorial](http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty) for doing that, as you may be aware of.)

Also, since I suggest you enable the issue tracker on https://github.com/Eurecat/abseil-cpp since it's the source that ROS binary is built from.

Anyways, thanks for taking the lead!

**Comment by facontidavide** [comment]
I must admit that the way I reorganized the files is a waste of time.
the only thing that I really need to add is package.xml and CMakeLists.txt.

This will make rebase also faster.

Thanks for your suggestions

**Comment by facontidavide** [comment]
I minimized the differences to make frequent rebase straightforward.
For simplicity, I packed cctz with absl. 

https://github.com/Eurecat/abseil-cpp/commits/master

Cheers
